'use strict';angular.module('data.directive',[]).directive('dtDir',function(){return{scope:{issue:'=issue'},restrict:'E',template:'<div>'
+'<h3>{{issue.top_category_name}}</h3>'
+'<h4>{{issue.category_name}}</h4>'
+'<div layout="row" layout-align="none none">'
+'<p md-truncate flex>{{issue.subject}}</p>'
+'<i>muokattu {{issue.last_modified_time | date : format : timezone}}</i>'
+'</div>'
+'</div>',replace:'true',controller:function($scope,$rootScope){$scope.id=$rootScope.getId();console.log('dtDir',$scope.id,$rootScope.created,': issue =',$scope.issue.id);$scope.$watch('issue',function(newValue,oldValue,scope){if(!angular.equals(newValue,oldValue)){console.debug('dtDir',$scope.id,': issue =>',newValue.id);}},true);$scope.$on('$destroy',function(){console.log('dtDir',$scope.id,$rootScope.destroyed);});}};});'use strict';angular.module('competition.directive',[]).directive('cpDir',function(){return{scope:{operation:'=operation'},restrict:'E',template:'<div layout="row" layout-align="none center">'
+'<span class="d-padding">{{operation.variableName}}</span><span class="d-padding">=</span><svro-dir variable-value=operation.variableValue ng-if="operation.type === setVariableOperationString"></svro-dir>'
+'</div>',replace:'true',controller:function($scope,$rootScope){$scope.id=$rootScope.getId();$scope.setVariableOperationString='fi.otavamedia.kilpailuautomaatti.domain.entity.rule.SetVariableOperation';$scope.$watch('operation',function(newValue,oldValue,scope){if(!angular.equals(newValue,oldValue)){console.debug('cpDir',$scope.id,': operation =>',newValue.id);}},true);$scope.$on('$destroy',function(){console.log('cpDir',$scope.id,$rootScope.destroyed);});}};});'use strict';angular.module('app.service',['ngResource']).factory('IssueResource',['$resource',function($resource){return $resource('https://dev.hel.fi:443/paatokset/v1/issue/',{},{get:{method:'GET',cache:false}});}]).factory('CategoryResource',['$resource',function($resource){return $resource('https://dev.hel.fi:443/paatokset/v1/category/',{},{get:{method:'GET',cache:false}});}]).service('AppService',['CategoryResource','IssueResource','$q','$timeout',function(CategoryResource,IssueResource,$q,$timeout){var self=this;var objects=null;var offset=0;var parameters=null;function issueParams(){if(!angular.isObject(parameters)){parameters={'category':null,'limit':null,'offset':0};}
else{parameters.offset=offset;}
return parameters;}
self.getIssueParams=function(){var params=issueParams();return angular.copy(params);};self.setLimit=function(limit){var params=issueParams();params.limit=limit?limit:20;parameters=params;};self.setCategory=function(category){var params=issueParams();params.category=category?category:null;parameters=params;};self.getCategories=function(params){var deferred=$q.defer();$timeout(function(){deferred.notify('started');CategoryResource.get(params).$promise.then(function(response){deferred.resolve(response);},function(error){deferred.reject(error);});},0);return deferred.promise;};self.getIssues=function(next){if(next!==true){objects=null;offset=0;}
var deferred=$q.defer();$timeout(function(){deferred.notify('started');IssueResource.get(issueParams()).$promise.then(function(response){offset=offset+response.objects.length;deferred.resolve({'objects':response.objects,'offset':offset,'total':response.meta.total_count});},function(error){deferred.reject(error);});},0);return deferred.promise;};}]);'use strict';angular.module('main.controller',[]).controller('mainController',function($rootScope,$scope,$state,AppService){console.log('mainController',$rootScope.created);var self=this;self.loadingIssues=false;self.issues=null;self.offset=null;self.total=null;self.more=null;self.getIssues=function(next){AppService.getIssues(next).then(function(response){console.debug('mainController.getIssues',response);if(next){var newIssues=angular.isArray(response.objects)?response.objects:[];self.issues.push.apply(self.issues,newIssues);}
else{self.issues=angular.isArray(response.objects)?response.objects:[];}
self.offset=response.offset;self.total=response.total;},function(error){console.error('mainController.getIssues',error);},function(notification){console.debug('mainController.getIssues: notify',notification);self.loadingIssues=true;}).finally(function(){console.debug('mainController.getIssues: finally');self.loadingIssues=false;var text;if(angular.isArray(self.issues)){var count=self.issues.length;text='Haettu: '+count+', ';self.more=self.total>count;}
text=text+'Yhteensä: '+self.total;$rootScope.showToast(text);});};self.openIssue=function(issue){console.log('mainController.openIssue',issue);if(angular.isObject(issue)){}};self.getIssuesByCategory=function(category){console.log('mainController.getIssuesByCategory',category);if(angular.isObject(category)){self.issues=null;self.getIssues();}};$scope.$on('$destroy',function(){console.log('mainController',$rootScope.destroyed);});});'use strict';angular.module('details.controller',[]).controller('detailsController',function($rootScope,$scope,$state,AppService,$mdToast){console.log('detailsController',$rootScope.created);var self=this;self.loadingIssues=false;self.issues=null;self.offset=null;self.total=null;self.more=null;self.getIssues=function(next){AppService.getIssues().then(function(response){console.debug('detailsController.getIssues',response);if(next){var newIssues=angular.isArray(response.objects)?response.objects:[];self.issues.push.apply(self.issues,newIssues);}
else{self.issues=angular.isArray(response.objects)?response.objects:[];}
self.offset=response.offset;self.total=response.total;},function(error){console.error('detailsController.getIssues',error);},function(notification){console.debug('detailsController.getIssues: notify',notification);self.loadingIssues=true;}).finally(function(){console.debug('detailsController.getIssues: finally');self.loadingIssues=false;var text;if(angular.isArray(self.issues)){var count=self.issues.length;text='Haettu: '+count+', ';self.more=self.total>count;}
text=text+'Yhteensä: '+self.total;$rootScope.showToast(text);});};self.openIssue=function(issue){console.log('detailsController.openIssue',issue);if(angular.isObject(issue)){}};$scope.$on('$destroy',function(){console.log('detailsController',$rootScope.destroyed);});});'use strict';angular.module('filter.controller',[]).controller('filterController',function($rootScope,$scope,$state,AppService){console.log('filterController',$rootScope.created);var self=this;self.loadingCategories=false;self.categories=null;self.selectedCategory=null;self.selectedCategory2=null;self.limit=null;function createFilterFor(category){return function filterFn(field){return(angular.lowercase(field.name).indexOf(angular.lowercase(category))===0);};}
self.getCategories=function(params){AppService.getCategories(params).then(function(response){console.debug('mainController.getCategories',response);self.categories=angular.isArray(response.objects)?response.objects:[];},function(error){console.error('mainController.getCategories',error);},function(notification){console.debug('mainController.getCategories: notify',notification);self.loadingCategories=true;}).finally(function(){console.debug('mainController.getCategories: finally');self.loadingCategories=false;});}
self.categoryChanged=function(category){console.log('filterController.categoryChanged',category);if(angular.isObject(category)){AppService.setCategory(category.id);}
else{AppService.setCategory();}};self.querySearch=function(query){return query?self.categories.filter(createFilterFor(query)):self.categories;};self.getIssueParams=function(){var issueParams=AppService.getIssueParams();self.limit=angular.isObject(issueParams)?issueParams.limit:null;};self.setLimit=function(limit){AppService.setLimit(limit);};self.getCategories();self.getIssueParams();$scope.$on('$destroy',function(){console.log('filterController',$rootScope.destroyed);});});'use strict';angular.module('competition.controller',[]).controller('competitionController',function($rootScope,$scope,$state,$http){console.log('competitionController',$rootScope.created);var self=this;self.competition=null;self.getCompetition=function(){$http.get('competition.json').then(function(response){console.debug('SUCCESS',response.data);self.competition=response.data;},function(error){console.error('ERROR');self.competition=null;});};$scope.$on('$destroy',function(){console.log('competitionController',$rootScope.destroyed);});});'use strict';angular.module('app.controllers',['main.controller','details.controller','filter.controller','competition.controller']).controller('appController',function($rootScope,$scope){console.log('appController',$rootScope.created);$scope.$on('$destroy',function(){console.log('appController',$rootScope.destroyed);});});'use strict';angular.module('app.routes',[]).config(['$stateProvider','$urlRouterProvider',function($stateProvider,$urlRouterProvider){$stateProvider.state("main",{url:'/main',views:{'appView':{templateUrl:'views/main.html',controller:'mainController',controllerAs:'ctrl'},'menuView':{templateUrl:'views/filter.html',controller:'filterController',controllerAs:'ctrl'}}}).state("details",{url:'/details',views:{'appView':{templateUrl:'views/details.html',controller:'detailsController',controllerAs:'ctrl'},'menuView':{templateUrl:'views/filter.html',controller:'filterController',controllerAs:'ctrl'}}}).state("competition",{url:'/competition',views:{'appView':{templateUrl:'views/competition.html',controller:'competitionController',controllerAs:'ctrl'},'menuView':{templateUrl:'views/filter.html',controller:'filterController',controllerAs:'ctrl'}}});$urlRouterProvider.otherwise('/main');}]);'use strict';angular.module("demoWebApp",['ui.router','app.service','app.controllers','app.routes','data.directive','competition.directive','set.variable.rule.operation.directive','operand.directive','ngMaterial','ngMdIcons','ngMessages']).config(function(){}).run(function($rootScope,$state,$mdToast){console.log('demoWebApp','RUN');$rootScope.created='CREATED';$rootScope.destroyed='DESTROYED';$rootScope.appName='DEMO APP';$rootScope.menuOpen=true;var id;$rootScope.goState=function(st){console.log('goState',st);if(angular.isString(st)){$state.go(st);}
else{$state.go('main');}};$rootScope.getId=function(){if(!id){id=10000;}
return id++;}
$rootScope.showToast=function(text,position){if(!angular.isString(position)){position='top right';}
$mdToast.show($mdToast.simple().textContent(text).position(position).hideDelay(3000));};$rootScope.toggleMenu=function(){$rootScope.menuOpen=$rootScope.menuOpen?false:true;};$rootScope.$on('$stateChangeStart',function(event,toState,toParams,fromState,fromParams,options){console.log('app.stateChangeStart:',toState);});$rootScope.$on('$stateNotFound',function(event,unfoundState,fromState,fromParams){console.log('app.stateNotFound:',unfoundState);});$rootScope.$on('$stateChangeSuccess',function(event,toState,toParams,fromState,fromParams){console.log('app.stateChangeSuccess:',toState);});$rootScope.$on('$stateChangeError',function(event,toState,toParams,fromState,fromParams,error){console.error('app.stateChangeError:',toState,error);});});